### PR TITLE
feature/click-command

### PR DESCRIPTION
**Pull request by exincore**
# Click Command
##### What?
- Run a command when the extension icon is clicked
##### Why?
- #18
##### How?
- `panelMenuButton.js` Run a command through `GLib.spawn_command_line_async` when clicked
- `prefs.js` et al. Add setting and text box for the command

Run command on click

### CODE REVIEW

**Comment by EXINCORE** [comment]
Standby as I unfudge this.

**Comment by win0err** [comment]
Hello! Thank you for the PR! Looks awesome!

I have a question: have you tested it in the following GNOME Shell versions: 3.38, 40, 41?

**Comment by EXINCORE** [comment]
Oops, I did not mean to do that.

> I have a question: have you tested it in the following GNOME Shell versions: 3.38, 40, 41?

It seems to function on 40 and 3.38 but I have not done anything extensive.

**Comment by win0err** [comment]
@exincore, sorry it wasn't merged.
The same functionality has been released in version 20: see https://github.com/win0err/gnome-runcat/pull/32. I'm closing the PR.

Many thanks for the PR! I'm waiting for the really cool feature in https://github.com/win0err/gnome-runcat/pull/24!

**Comment by jack23247** [comment]
@win0err May I vouch for this PR to be reopened? The functionality implemented here is different by the behavior introduced in version 20. Namely, this PR allows:

- The user to specify a custom command, which currently does not seem to be possible
- The command to be run by left-clicking on the widget. Currently by doing that, the drop-down menu is presented instead.

It would be interesting to combine the functionality of this PR with what is currently possible in runcat 21 by allowing the user to choose the default behavior when left-clicking, specifying the executable they want to launch and customizing the text presented in the drop-down menu (which would still be accessible by right-clicking).

**Comment by jack23247** [comment]
You're welcome, and thank you for considering my suggestion. Keep up the good work! :+1:

**Pull request closed without merging**
