### PR TITLE
Add multi icon pack support 🐱

### PR DESCRIPTION
**Pull request by JAFB321**
Features:
- Ability to select more icon packs from the extension settings
- Multi image extension support 
- Change the animation speed for each icon pack (from code)

Now you can go to the settings and select the pack in the combobox:
image
image

I don't have more cool icons, I just added a dancing parrot and funny walking chicken. But this changes make us able to add more icon packs in a easy way.  

## How to add more icon packs

1.  Add icons files (same folder structure): 

image

2. Prefs - Add it to settings
image
image

3.- Then add the IconProvider preset
image
The `getIconProvider` function return an instance of IconProvider with the preset of each icon pack.
Note that the IconProvider class now has the following params:
- name: name of the icon pack
- ext: icons files extension
- spritesCount
- speed: is for adjust animation speed  (default: 1)

## Enjoy!
Any feedback is welcome, I like your project and I can contribute to add more features if you want ! :)

### CODE REVIEW

**Comment by win0err** [comment]
Hello, @JAFB321! Thanks for awesome PR!
The feature you introduced is really cool! 

I want to mention the following things:
1. Image format. 
GIF is really terrible format. It doesn't support partial (alpha-channel) transparency. It looks awful on white or transparent top bars.
PNG is better, but it's not scalable. I'm not sure that PNGs will look nice on 4k/5k monitors.
Let's use SVGs. It's a standard for graphics in Linux (especially on GNOME Shell's top bar).

2. Licence.
We need to have CC licensed images to be freely published on EOG, repositories, etc. 

For Party Carrot 

For example, https://codepen.io/nathangath/pen/RgvzVY/

`y = 5000/(sqrt(x+30) * runnerSpeedCoef) - 400`

**Comment by win0err** [comment]
Hello, @JAFB321! Thanks for awesome PR!
The feature you introduced is really cool! 

I want to mention the following things:
1. Image format
GIF is really terrible format. It doesn't support partial (alpha-channel) transparency. It looks awful on white or transparent top bars. PNG is better, but it's not scalable. I'm not sure that PNGs will look nice on 4k/5k monitors. 
\
Let's use SVGs. It's a standard for graphics in Linux (especially on GNOME Shell's top bar). 
We can draw an SVGs with Parti parrot, but chicken GIF should be removed, sorry.

2. Licence
We need to have CC-licensed images to be freely published on EOG, repositories, etc. 
\
About Party Carrot:
I found a [repo](https://github.com/jmhobbs/cultofthepartyparrot.com) with some source code. For example, [parrot.svg](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/main/src/parrot.svg) is licensed under [Creative Commons](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/main/LICENSE). Link for inspiration: https://codepen.io/nathangath/pen/RgvzVY/. We need to draw/create all missing states. I can help you with this activity.
\
Another suggestion is the following: I think that it would be better if the parrot will be filled with `#bebebe` color. It's another standard of GNOME top bar icons.

3. Speed
I mentioned that you have introduced a new coefficient `runnerSpeedCoef` in formula:
`y = 5000/sqrt(x+30) * runnerSpeedCoef - 400`
I want to mention that `runnerSpeedCoef` could be automatically calculated.
\
I suggest the following configuration:
`runnerSpeedCoef = 5 / spritesCount`
`y = (5000/sqrt(x+30) - 400) * runnerSpeedCoef`.
\
It will give us the same time limit for playing all sprites. For example, when x (CPU utilization) is 5:
`spritesCount = 10: y = 222.577127364`,
`spritesCount = 5: y = 445.154254729`, etc.

P.S. I've created a branch called `feature/different-runners`. Could you send this PR to the [feature/different-runners](https://github.com/win0err/gnome-runcat/tree/feature/different-runners), not `master` branch? Thanks!

**Comment by JAFB321** [comment]
Hi @win0err  Thank you very much for the feedback! 
I'll work on that soon and make a PR to `feature/different-runners` branch 👍🏻

**Comment by win0err** [comment]
> Hi @win0err Thank you very much for the feedback! I'll work on that soon and make a PR to `feature/different-runners` branch 👍🏻

Thank you! If you have any questions — feel free to ask!

**Comment by win0err** [comment]
Already implemented in #33

**Comment by evanslify** [comment]
Seems like the functionalities exists only in feature/v22 branch instead of master?

**Pull request closed without merging**
