### PR TITLE
Feature/runner packs

### PR DESCRIPTION
**Pull request by exincore**
# Runner Packs

RELIES UPON #24

##### What?

- Other runner icons/animations can be selected

##### Why?

- #2
- #23 has no activity

##### How?

- `panelMenuButton.js` loads different icon sets depending on user setting
- `prefs.js` et al. has a enum selector for choosing the runner pack
- Brand new metronome runner, created by me!

https://user-images.githubusercontent.com/44628275/198193029-cdd9c6a9-5222-413a-89ca-2c56fe26bcb3.mp4

Screenshot from 2022-10-26 22-41-22

##### To-do

- [ ] Display runner thumbnail in settings menu and dropdown

### CODE REVIEW

**Comment by win0err** [comment]
Thanks for your awesome work! Metronome looks very cool, feel free to add yourself here: https://github.com/win0err/gnome-runcat/blob/master/src/resources/ui/preferences.ui#L83

**Comment by win0err** [comment]
> Display runner thumbnail in settings menu and dropdown

In my opinion, this does not make much sense because the settings are applied automatically and immediately

**Comment by win0err** [comment]
I suggest the following plan:
1. Merge animated idle (#24) feature;
2. Merge this feature.

**Comment by win0err** [comment]
I've merged #24 into `feature/v22` branch.

Please, resolve conflicts and mark the PR as non-draft.
PR looks good to me. I'm ready to merge it after resolving conflicts.

**Comment by win0err** [comment]
Thank you for great work, @exincore!

I'll add some features also and publish a new version in a month.

**Comment by JAFB321** [comment]
Awesomee work!

**Comment by evanslify** [comment]
The commits are in v22 branch and not in main?

**Comment by win0err** [comment]
> The commits are in v22 branch and not in main?

Yes. That’s a development branch.
You may clone the repo, checkout the branch, than run `make install`

**Comment by evanslify** [comment]
I understand, however we are now on v23 - just wondering if there's anything needed to do to merge this back into master. I'll be more than happy to produce a cherry-picked/rebased PR of this feature against master.

**Pull request merged**
